export const ACTION_TYPES = Object.freeze({
  COUNTRIES_FETCH_START: 'COUNTRIES_FETCH_START',
  COUNTRIES_FETCH_SUCCESS: 'COUNTRIES_FETCH_SUCCESS',
  COUNTRIES_FETCH_ERROR: 'COUNTRIES_FETCH_ERROR',
  COUNTRY_FETCH_START: 'COUNTRY_FETCH_START',
  COUNTRY_FETCH_SUCCESS: 'COUNTRY_FETCH_SUCCESS',
  COUNTRY_FETCH_ERROR: 'COUNTRY_FETCH_ERROR',
});
